"""empty message

Revision ID: 87fa5fcc6212
Revises: 
Create Date: 2021-08-28 23:02:04.730778

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '87fa5fcc6212'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'release_date',
               existing_type=sa.DATE(),
               nullable=True)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('movies', 'release_date',
               existing_type=sa.DATE(),
               nullable=False)
    # ### end Alembic commands ###
